added favicon

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -14,13 +14,12 @@ python3 util/buildtoc.py
 # make build directory and copy original files there for preflighting
 rm -rf build
 mkdir build
-cp robots.txt *.css build/
+cp robots.txt .htaccess *.css *.ico build/
 cp -R j build/
 cp -R i build/
 cp -R f build/
 rm -f examples/*.pyc
 cp -R examples build/
-cp .htaccess build/
 mkdir build/fonts-original
 cp fonts-original/*.tar.gz build/fonts-original/
 
@@ -89,7 +88,7 @@ sed -i -e "s|=http:|=|g" build/*.html && \
 
 # set file permissions (hg resets these, don't know why)
 chmod 755 build/examples build/j build/i build/f build/fonts-original && \
-    chmod 644 build/*.html build/*.txt build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess build/fonts-original/*.tar.gz || die "Failed to reset file permissions"
+    chmod 644 build/*.html build/*.txt build/*.ico build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess build/fonts-original/*.tar.gz || die "Failed to reset file permissions"
 
 #die "Intentionally aborting without publishing"
 # ship it!
@@ -102,7 +101,7 @@ rsync -essh -a --exclude="*.mp4" --exclude="*.ogv" build/i/* build/i/.htaccess d
     echo -n "." && \
     rsync -essh -a build/f/*.ttf build/f/*.eot build/f/.htaccess diveintomark.org:~/web/diveintohtml5.org/f/ && \
     echo -n "." && \
-    rsync -essh -a build/examples build/*.txt build/*.html build/.htaccess build/fonts-original diveintomark.org:~/web/diveintohtml5.org/ && \
+    rsync -essh -a build/examples build/*.txt build/*.ico build/*.html build/.htaccess build/fonts-original diveintomark.org:~/web/diveintohtml5.org/ && \
     echo "." || die "Failed to publish to remote server"
 
 [ -n "$(which Snarl_CMD 2>/dev/null)" ] && Snarl_CMD snShowMessage 10 "Dive Into HTML5" "Published." "C:\Users\pilgrim\site-lisp\todochiku-icons\clean.png"
