migrate to async Google Analytics script, optimize build process

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -40,12 +40,6 @@ ls build/*.html | sed -e "s|build/|http://diveintohtml5.org/|g" -e "s|/index.htm
 
 echo "adding evil tracking code"
 
-# add Google Analytics script
-for f in build/*.html; do
-  cat "$f" j/ga.js > build/tmp && \
-      mv build/tmp "$f" || die "Could not add tracking code to $f"
-done
-
 # minimize JS and CSS
 echo "minimizing JS"
 revision=`hg log|grep changeset|cut -d":" -f3|head -1`
@@ -53,11 +47,21 @@ java -jar util/yuicompressor-2.4.2.jar build/j/dih5.js > build/j/dih5.min.js || 
 java -jar util/yuicompressor-2.4.2.jar build/j/canvastext-fx3.js > build/j/canvastext-fx3.min.js || die "Failed to minimize JS"
 java -jar util/yuicompressor-2.4.2.jar build/j/html5-video.js > build/j/html5-video.min.js || die "Failed to minimize JS"
 
+echo "minimizing CSS"
+sed -i -e "s|url(i/|url(//d.wearehugh.com/dih5/|g" build/screen.css || die "Failed to inline CSS"
+java -jar util/yuicompressor-2.4.2.jar build/screen.css > build/$revision.css && \
+    sed -i -e "s|;}|}|g" build/$revision.css || die "Failed to minimize CSS"
+
 # combine jQuery, Modernizr, other 3rd party scripts, and our own scripts
 echo "combining JS"
 cat build/j/legal.js build/j/jquery.min.js build/j/modernizr.min.js build/j/canvastext-fx3.min.js build/j/dih5.min.js > build/j/$revision.js && \
 cat build/j/legal.js build/j/gears_init.min.js build/j/geo.min.js > build/j/$revision-maps.js && \
-cat build/j/legal.js build/j/flowplayer-3.1.4.min.js build/j/html5-video.min.js > build/j/$revision-video.js && \
+cat build/j/legal.js build/j/flowplayer-3.1.4.min.js build/j/html5-video.min.js > build/j/$revision-video.js || die "Failed to combine JS"
+
+# consolidate JS links, inline CSS, minimize URLs, add Google Analytics script
+echo "inlining CSS, minimizing URLs, adding new-and-improved evil tracking code"
+css=`cat build/$revision.css`
+ga=`cat j/ga.js`
 sed -i -e "s|<script src=j/jquery.js></script>||g" \
        -e "s|<script src=j/modernizr.js></script>||g" \
        -e "s|<script src=j/gears_init.js></script>||g" \
@@ -65,28 +69,19 @@ sed -i -e "s|<script src=j/jquery.js></script>||g" \
        -e "s|<script src=j/canvastext-fx3.js></script>||g" \
        -e "s|<script src=j/flowplayer-3.1.4.min.js></script>||g" \
        -e "s|<script src=j/html5-video.js>|<script src=j/${revision}-video.js>|g" \
-       -e "s|<script src=j/dih5.js>|<script src=j/${revision}.js>|g" build/*.html || die "Failed to combine JS"
-
-echo "minimizing CSS"
-sed -i -e "s|url(i/|url(//d.wearehugh.com/dih5/|g" build/screen.css || die "Failed to inline CSS"
-java -jar util/yuicompressor-2.4.2.jar build/screen.css > build/$revision.css && \
-    sed -i -e "s|;}|}|g" build/$revision.css || die "Failed to minimize CSS"
-
-# put CSS inline
-echo "inlining CSS"
-css=`cat build/$revision.css`
-sed -i -e "s|<link rel=stylesheet href=screen.css>|<style>${css}</style>|g" -e "s|</style><style>||g" build/*.html || die "Failed to inline CSS"
+       -e "s|<script src=j/dih5.js>|<script src=j/${revision}.js>|g" \
+       -e "s|<link rel=stylesheet href=screen.css>|<style>${css}</style>|g" \
+       -e "s|</style><style>||g" \
+       -e "s|</style>|</style>${ga}|g" \
+       -e "s|=http:|=|g" \
+       -e "s|href=index.html|href=/|g" \
+  build/*.html || die "Failed to combine JS"
 
 # remove unused CSS properties on a page-by-page basis
 echo "removing unused CSS"
 for f in build/*.html; do
   python2.6 util/lesscss.py "$f" || die "Failed to remove unused CSS"
 done
-
-# minimize URLs
-echo "minimizing URLs"
-sed -i -e "s|=http:|=|g" build/*.html && \
-    sed -i -e "s|href=index.html|href=/|g" build/*.html || die "Failed to minimize URLs"
 
 # set file permissions (hg resets these, don't know why)
 chmod 755 build/examples build/j build/i build/f build/fonts-original && \
