mobile stylesheet

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -50,7 +50,9 @@ java -jar util/compiler.jar -js build/j/html5-video.js > build/j/html5-video.min
 echo "minimizing CSS"
 sed -i -e "s|url(i/|url(//d.wearehugh.com/dih5/|g" build/screen.css || die "Failed to inline CSS"
 java -jar util/yuicompressor-2.4.2.jar build/screen.css > build/$revision.css && \
-    sed -i -e "s|;}|}|g" build/$revision.css || die "Failed to minimize CSS"
+    java -jar util/yuicompressor-2.4.2.jar build/mobile.css > build/m-$revision.css && \
+    sed -i -e "s|;}|}|g" build/$revision.css && \
+    sed -i -e "s|;}|}|g" build/m-$revision.css || die "Failed to minimize CSS"
 
 # combine jQuery, Modernizr, other 3rd party scripts, and our own scripts
 echo "combining JS"
@@ -61,6 +63,7 @@ cat build/j/legal.js build/j/flowplayer-3.1.4.min.js build/j/html5-video.min.js 
 # consolidate JS links, inline CSS, minimize URLs, add Google Analytics script
 echo "inlining CSS, minimizing URLs, adding new-and-improved evil tracking code"
 css=`cat build/$revision.css`
+mobilecss=`cat build/m-$revision.css`
 ga=`cat j/ga.js`
 sed -i -e "s|<script src=j/jquery.js></script>||g" \
        -e "s|<script src=j/modernizr.js></script>||g" \
@@ -71,6 +74,7 @@ sed -i -e "s|<script src=j/jquery.js></script>||g" \
        -e "s|<script src=j/html5-video.js>|<script src=j/${revision}-video.js>|g" \
        -e "s|<script src=j/dih5.js>|<script src=j/${revision}.js>|g" \
        -e "s|<link rel=stylesheet href=screen.css>|<style>${css}</style>|g" \
+       -e "s|<link rel=stylesheet media='only screen and (max-device-width: 480px)' href=mobile.css>|<style>@media screen and (max-device-width:480px){${mobilecss}}</style>|g" \
        -e "s|</style><style>||g" \
        -e "s|</style>|</style>${ga}|g" \
        -e "s|=http:|=|g" \
@@ -87,7 +91,7 @@ done
 chmod 755 build/examples build/j build/i build/f build/fonts-original && \
     chmod 644 build/*.html build/*.txt build/*.ico build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess build/fonts-original/*.tar.gz || die "Failed to reset file permissions"
 
-#die "Intentionally aborting without publishing"
+die "Intentionally aborting without publishing"
 # ship it!
 echo -n "publishing"
 rsync -essh -a --exclude="*.mp4" --exclude="*.ogv" build/i/* build/i/.htaccess diveintomark.org:~/web/wearehugh.com/dih5/ && \
