build fiddling

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -13,6 +13,7 @@ mkdir build
 cp robots.txt *.css build/
 cp -R j build/
 cp -R i build/
+cp -R f build/
 rm -f examples/*.pyc
 cp -R examples build/
 cp .htaccess build/
@@ -69,14 +70,16 @@ sed -i -e "s|=http:|=|g" build/*.html && \
     sed -i -e "s|href=index.html|href=/|g" build/*.html || die "Failed to minimize URLs"
 
 # set file permissions (hg resets these, don't know why)
-chmod 755 build/examples build/j build/i && \
-    chmod 644 build/*.html build/*.txt build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/.htaccess || die "Failed to reset file permissions"
+chmod 755 build/examples build/j build/i build/f && \
+    chmod 644 build/*.html build/*.txt build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess || die "Failed to reset file permissions"
 
 # ship it!
 echo -n "publishing"
 rsync -essh -a build/i/* build/i/.htaccess diveintomark.org:~/web/wearehugh.com/dih5/ && \
     echo -n "." && \
     rsync -essh -a build/j/$revision.js build/j/html5.js build/j/.htaccess diveintomark.org:~/web/diveintohtml5.org/j/ && \
+    echo -n "." && \
+    rsync -essh -a build/f/*.ttf build/f/.htaccess diveintomark.org:~/web/diveintohtml5.org/f/ && \
     echo -n "." && \
     rsync -essh -a build/examples build/*.txt build/*.html build/.htaccess diveintomark.org:~/web/diveintohtml5.org/ && \
     echo "." || die "Failed to publish to remote server"
