build fixes

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -52,15 +52,18 @@ echo "minimizing JS"
 revision=`hg log|grep changeset|cut -d":" -f3|head -1`
 java -jar util/yuicompressor-2.4.2.jar build/j/dih5.js > build/j/dih5.min.js || die "Failed to minimize JS"
 java -jar util/yuicompressor-2.4.2.jar build/j/canvastext-fx3.js > build/j/canvastext-fx3.min.js || die "Failed to minimize JS"
+java -jar util/yuicompressor-2.4.2.jar build/j/html5-video.js > build/j/html5-video.min.js || die "Failed to minimize JS"
 
 # combine jQuery, Modernizr, other 3rd party scripts, and our own scripts
 echo "combining JS"
-cat build/j/legal.js build/j/jquery.min.js build/j/modernizr.min.js build/j/gears_init.min.js build/j/geo.min.js build/j/canvastext-fx3.min.js build/j/dih5.min.js > build/j/$revision.js && \
+cat build/j/legal.js build/j/jquery.min.js build/j/modernizr.min.js build/j/gears_init.min.js build/j/geo.min.js build/j/canvastext-fx3.min.js build/j/flowplayer-3.1.4.min.js build/j/html5-video.min.js build/j/dih5.min.js > build/j/$revision.js && \
     sed -i -e "s|<script src=j/jquery.js></script>||g" build/*.html && \
     sed -i -e "s|<script src=j/modernizr.js></script>||g" build/*.html && \
     sed -i -e "s|<script src=j/gears_init.js></script>||g" build/*.html && \
     sed -i -e "s|<script src=j/geo.js></script>||g" build/*.html && \
     sed -i -e "s|<script src=j/canvastext-fx3.js></script>||g" build/*.html && \
+    sed -i -e "s|<script src=j/flowplayer-3.1.4.min.js></script>||g" build/*.html && \
+    sed -i -e "s|<script src=j/html5-video.js></script>||g" build/*.html && \
     sed -i -e "s|<script src=j/dih5.js>|<script src=j/${revision}.js>|g" build/*.html || die "Failed to combine JS"
 
 echo "minimizing CSS"
@@ -92,7 +95,7 @@ chmod 755 build/examples build/j build/i build/f build/fonts-original && \
 echo -n "publishing"
 rsync -essh -a build/i/* build/i/.htaccess diveintomark.org:~/web/wearehugh.com/dih5/ && \
     echo -n "." && \
-    rsync -essh -a build/j/$revision.js build/j/html5.js build/j/excanvas.min.js build/j/.htaccess diveintomark.org:~/web/diveintohtml5.org/j/ && \
+    rsync -essh -a build/j/$revision.js build/j/html5.js build/j/excanvas.min.js build/j/*.swf build/j/.htaccess diveintomark.org:~/web/diveintohtml5.org/j/ && \
     echo -n "." && \
     rsync -essh -a build/f/*.ttf build/f/*.eot build/f/.htaccess diveintomark.org:~/web/diveintohtml5.org/f/ && \
     echo -n "." && \
