add font sources to build process

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -17,6 +17,8 @@ cp -R f build/
 rm -f examples/*.pyc
 cp -R examples build/
 cp .htaccess build/
+mkdir build/fonts-original
+cp fonts-original/*.tar.gz build/fonts-original/
 
 echo "minimizing HTML"
 
@@ -68,8 +70,8 @@ sed -i -e "s|=http:|=|g" build/*.html && \
     sed -i -e "s|href=index.html|href=/|g" build/*.html || die "Failed to minimize URLs"
 
 # set file permissions (hg resets these, don't know why)
-chmod 755 build/examples build/j build/i build/f && \
-    chmod 644 build/*.html build/*.txt build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess || die "Failed to reset file permissions"
+chmod 755 build/examples build/j build/i build/f build/fonts-original && \
+    chmod 644 build/*.html build/*.txt build/examples/* build/examples/.htaccess build/j/* build/j/.htaccess build/i/* build/i/.htaccess build/f/* build/f/.htaccess build/.htaccess build/fonts-original/*.tar.gz || die "Failed to reset file permissions"
 
 # ship it!
 echo -n "publishing"
@@ -79,5 +81,5 @@ rsync -essh -a build/i/* build/i/.htaccess diveintomark.org:~/web/wearehugh.com/
     echo -n "." && \
     rsync -essh -a build/f/*.ttf build/f/*.eot build/f/.htaccess diveintomark.org:~/web/diveintohtml5.org/f/ && \
     echo -n "." && \
-    rsync -essh -a build/examples build/*.txt build/*.html build/.htaccess diveintomark.org:~/web/diveintohtml5.org/ && \
+    rsync -essh -a build/examples build/*.txt build/*.html build/.htaccess build/fonts-original diveintomark.org:~/web/diveintohtml5.org/ && \
     echo "." || die "Failed to publish to remote server"
